Project.MVCUI/Areas/Administrator/Controllers/AdminProductController.cs
using Project.BLL.DesignPatterns.RepositoryPattern.ConcRep;
using Project.COMMON.MyTools;
using Project.MODEL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Areas.Administrator.Controllers
{
    public class AdminProductController : Controller
    {
        ProductRepository pRep;
        CategoryRepository cRep;

        public AdminProductController()
        {
            cRep = new CategoryRepository();
            pRep = new ProductRepository();
        }
        // GET: Administrator/AdminProduct
        public ActionResult ProductList()
        {
            return View(pRep.GetAll());
        }

        public ActionResult AddProduct()
        {
            return View(Tuple.Create(new Product(),cRep.GetActives()));
        }

        [HttpPost]
        public ActionResult AddProduct([Bind(Prefix ="Item1")] Product item,HttpPostedFileBase resim)
        {
            item.ImagePath = ImageUploader.UploadImage("~/Pictures/", resim);
            pRep.Add(item);
            return RedirectToAction("ProductList");
        }

        public ActionResult UpdateProduct()
        {
            

            return View();
        }

        [HttpPost]
        public ActionResult UpdateProduct(Product item)
        {
            Product guncellenecek = pRep.Find(item.ID);
            guncellenecek.ProductName = item.ProductName;
            guncellenecek.UnitPrice = item.UnitPrice;
            guncellenecek.UnitsInStock = item.UnitsInStock;
            pRep.Update(item);
            return RedirectToAction("ProductList");
        }

        public ActionResult DeleteProduct(int id)
        {
            pRep.Delete(pRep.Find(id));
            return RedirectToAction("ProductList");
        }
    }
}

Project.MVCUI/Areas/Administrator/Views/AdminProduct/AddProduct.cshtml
@model Tuple<Product,List<Category>>
@{
    ViewBag.Title = "AddProduct";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Ürün Ekleme Sayfası
            </header>
            <div class="panel-body">
                <div class=" form">

                    @using (Html.BeginForm("AddProduct", "AdminProduct", FormMethod.Post, new { @class = "cmxform form-horizontal tasi-form,", enctype = "multipart/form-data" }))
                    {
                        <div class="form-group ">
                            <label for="cname" class="control-label col-lg-2">Ürün Adı</label>
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x => x.Item1.ProductName, new { @class = "form-control" })

                            </div>

                        </div>

                        <div class="form-group ">
                            <label for="cname" class="control-label col-lg-2">Ürün Fiyatı</label>
                            <div class="col-lg-10">

                                @Html.TextBoxFor(x => x.Item1.UnitPrice, new { @class = "form-control", type = "number" })


                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="cname" class="control-label col-lg-2">Ürün Stok</label>
                            <div class="col-lg-10">

                                @Html.TextBoxFor(x => x.Item1.UnitsInStock, new { @class = "form-control", type = "number" })


                            </div>
                        </div>




                        <div class="form-group ">
                            <label for="cname" class="control-label col-lg-2">Ürün Kategorisi</label>
                            <div class="col-lg-10">

                                @Html.DropDownListFor(x => x.Item1.CategoryID, new SelectList(Model.Item2, "ID", "CategoryName"), "Lütfen Seciniz", new { @class = "form-control" })


                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-2">Image Upload</label>
                            <div class="col-md-9">
                                <div class="fileupload fileupload-new" data-provides="fileupload">
                                    <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                                        <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" />
                                    </div>
                                    <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
                                    <div>
                                        <span class="btn btn-white btn-file">
                                            <span class="fileupload-new"><i class="icon-paper-clip"></i> Select image</span>
                                            <span class="fileupload-exists"><i class="icon-undo"></i> Change</span>
                                            <input name="resim" type="file" class="default" />
                                        </span>
                                        <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="icon-trash"></i> Remove</a>
                                    </div>
                                </div>

                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-danger" type="submit">Kaydet</button>

                            </div>
                        </div>
                    }



                </div>

            </div>
        </section>
    </div>
</div>

Project.MVCUI/Areas/Administrator/Views/AdminProduct/ProductList.cshtml
@model List<Product>
@{
    ViewBag.Title = "ProductList";
}

<section class="panel">
    <header class="panel-heading">
        Ürün eklemek için @Html.ActionLink("tıklayınız", "AddProduct")
    </header>
    <div class="panel-body">
        <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
                <thead>
                    <tr>
                        <th>Product ID</th>
                        <th>Ürün İsmi</th>
                        <th>Ürün Fiyatı</th>
                        <th>Ürün Stogu</th>
                        <th class="hidden-phone">Veri Durumu</th>
                        <th class="hidden-phone">Güncelleme</th>
                        <th class="hidden-phone">Silme</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (Product item in Model)
                    {
                    <tr class="gradeX">
                        <td>@item.ID</td>
                        <td>@item.ProductName</td>
                        <td>
                            @item.UnitPrice
                        </td>
                        <td>
                            @item.UnitsInStock
                        </td>
                        <td class="hidden-phone">@item.Status</td>
                        <td class="center hidden-phone">  @Html.ActionLink("Güncelle", "UpdateProduct", new { id = item.ID }, new { @class = "btn btn-warning" })     </td>
                        <td class="center hidden-phone">  @Html.ActionLink("Sil", "DeleteProduct", new { id = item.ID }, new { @class = "btn btn-danger" })        </td>
                    </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</section>

<script type="text/javascript">
/* Formating function for row details */
      function fnFormatDetails ( oTable, nTr )
      {
          var aData = oTable.fnGetData( nTr );
          var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
          sOut += '<tr><td>Rendering engine:</td><td><a href="/Administrator/AdminProduct/ProductDetail/' + aData[1] + '">' + aData[2] + ' details</a>  </td></tr>';
          sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
          sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
          sOut += '</table>';

          return sOut;
      }

      $(document).ready(function() {
          /*
           * Insert a 'details' column to the table
           */
          var nCloneTh = document.createElement( 'th' );
          var nCloneTd = document.createElement( 'td' );
          nCloneTd.innerHTML = '<img src="/OuterTools/FlatAdmin/assets/advanced-datatable/examples/examples_support/details_open.png">';
          nCloneTd.className = "center";

          $('#hidden-table-info thead tr').each( function () {
              this.insertBefore( nCloneTh, this.childNodes[0] );
          } );

          $('#hidden-table-info tbody tr').each( function () {
              this.insertBefore(  nCloneTd.cloneNode( true ), this.childNodes[0] );
          } );

          /*
           * Initialse DataTables, with no sorting on the 'details' column
           */
          var oTable = $('#hidden-table-info').dataTable( {
              "aoColumnDefs": [
                  { "bSortable": false, "aTargets": [ 0 ] }
              ],
              "aaSorting": [[1, 'asc']]
          });

          /* Add event listener for opening and closing details
           * Note that the indicator for showing which row is open is not controlled by DataTables,
           * rather it is done here
           */
          $('#hidden-table-info tbody td img').live('click', function () {
              var nTr = $(this).parents('tr')[0];
              if ( oTable.fnIsOpen(nTr) )
              {
                  /* This row is already open - close it */
                  this.src = "/OuterTools/FlatAdmin/assets/advanced-datatable/examples/examples_support/details_open.png";
                  oTable.fnClose( nTr );
              }
              else
              {
                  /* Open this row */
                  this.src = "/OuterTools/FlatAdmin/assets/advanced-datatable/examples/examples_support/details_close.png";
                  oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
              }
          } );
      } );</script>