Project.MVCUI/Areas/Administrator/Controllers/AdminCategoryController.cs
using Project.BLL.DesignPatterns.RepositoryPattern.ConcRep;
using Project.MODEL.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.MVCUI.Areas.Administrator.Controllers
{
    public class AdminCategoryController : Controller
    {

        CategoryRepository crep;

        public AdminCategoryController()
        {
            crep = new CategoryRepository();
        }



        public ActionResult CategoryList()
        {

            return View(crep.GetAll());
        }


        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category item)
        {
            crep.Add(item);
            return RedirectToAction("CategoryList");
        }

        public ActionResult UpdateCategory(int id)
        {
            return View(crep.Find(id));
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category item)
        {
            crep.Update(item);
            return RedirectToAction("CategoryList");
        }

        public ActionResult DeleteCategory(int id)
        {
            crep.Delete(crep.Find(id));
            return RedirectToAction("CategoryList");
        }
    }
}

Project.MVCUI/Areas/Administrator/Views/AdminCategory/AddCategory.cshtml
@model Category
@{
    ViewBag.Title = "Kategori Ekleme Sayfası";
}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    Kategori Ekleme Sayfası
                </header>
                <div class="panel-body">
                    <div class=" form">
                        <form class="cmxform form-horizontal tasi-form" id="commentForm" method="post" action="/Administrator/AdminCategory/AddCategory">

                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">Kategori Adı</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cname" name="CategoryName" minlength="2" type="text" required />
                                </div>
                             
                            </div>

                            <div class="form-group ">
                                <label for="cname" class="control-label col-lg-2">Kategori Açıklaması</label>
                                <div class="col-lg-10">
                                    <input class=" form-control" id="cd" name="Description" minlength="2" type="text" required />
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-lg-offset-2 col-lg-10">
                                    <button class="btn btn-danger" type="submit">Kaydet</button>
                                    
                                </div>
                            </div>

                        </form>
                    </div>

                </div>
            </section>
        </div>
    </div>

Project.MVCUI/Areas/Administrator/Views/AdminCategory/CategoryList.cshtml
@model List<Category>
@{
    ViewBag.Title = "CategoryList";
}

<section class="panel">
    <header class="panel-heading">
        Kategori eklemek için @Html.ActionLink("tıklayınız","AddCategory")
    </header>
    <div class="panel-body">
        <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="hidden-table-info">
                <thead>
                    <tr>
                        <th>Kategori ID</th>
                        <th>Kategori İsmi</th>
                        <th>Açıklaması</th>
                        <th class="hidden-phone">Veri Durumu</th>
                        <th class="hidden-phone">Güncelleme</th>
                        <th class="hidden-phone">Silme</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (Category item in Model)
                    {
                        <tr class="gradeX">
                            <td>@item.ID</td>
                            <td>@item.CategoryName</td>
                            <td>
                               @item.Description
                            </td>
                            <td class="hidden-phone">@item.Status</td>
                            <td class="center hidden-phone">  @Html.ActionLink("Güncelle","UpdateCategory",new { id = item.ID },new {@class="btn btn-warning" })     </td>
                            <td class="center hidden-phone">  @Html.ActionLink("Sil", "DeleteCategory", new { id = item.ID }, new { @class = "btn btn-danger" })        </td>
                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</section>

<script type="text/javascript">/* Formating function for row details */
      function fnFormatDetails ( oTable, nTr )
      {
          var aData = oTable.fnGetData( nTr );
          var sOut = '<table cellpadding="5" cellspacing="0" border="0" style="padding-left:50px;">';
          sOut += '<tr><td>Rendering engine:</td><td><a href="/Administrator/AdminCategory/CategoryDetail/' + aData[1] + '">' + aData[2] + ' details</a>  </td></tr>';
          sOut += '<tr><td>Link to source:</td><td>Could provide a link here</td></tr>';
          sOut += '<tr><td>Extra info:</td><td>And any further details here (images etc)</td></tr>';
          sOut += '</table>';

          return sOut;
      }

      $(document).ready(function() {
          /*
           * Insert a 'details' column to the table
           */
          var nCloneTh = document.createElement( 'th' );
          var nCloneTd = document.createElement( 'td' );
          nCloneTd.innerHTML = '<img src="/OuterTools/FlatAdmin/assets/advanced-datatable/examples/examples_support/details_open.png">';
          nCloneTd.className = "center";

          $('#hidden-table-info thead tr').each( function () {
              this.insertBefore( nCloneTh, this.childNodes[0] );
          } );

          $('#hidden-table-info tbody tr').each( function () {
              this.insertBefore(  nCloneTd.cloneNode( true ), this.childNodes[0] );
          } );

          /*
           * Initialse DataTables, with no sorting on the 'details' column
           */
          var oTable = $('#hidden-table-info').dataTable( {
              "aoColumnDefs": [
                  { "bSortable": false, "aTargets": [ 0 ] }
              ],
              "aaSorting": [[1, 'asc']]
          });

          /* Add event listener for opening and closing details
           * Note that the indicator for showing which row is open is not controlled by DataTables,
           * rather it is done here
           */
          $('#hidden-table-info tbody td img').live('click', function () {
              var nTr = $(this).parents('tr')[0];
              if ( oTable.fnIsOpen(nTr) )
              {
                  /* This row is already open - close it */
                  this.src = "/OuterTools/FlatAdmin/assets/advanced-datatable/examples/examples_support/details_open.png";
                  oTable.fnClose( nTr );
              }
              else
              {
                  /* Open this row */
                  this.src = "/OuterTools/FlatAdmin/assets/advanced-datatable/examples/examples_support/details_close.png";
                  oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
              }
          } );
      } );</script>

Project.MVCUI/Areas/Administrator/Views/AdminCategory/UpdateCategory.cshtml
@model Category
@{
    ViewBag.Title = "UpdateCategory";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
               Kategori Güncelleme Sayfası
            </header>
            <div class="panel-body">
                <div class="form">

                    @using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post, new { @class = "cmxform form-horizontal tasi-form" }))
                    {
                        @Html.HiddenFor(x => x.ID)

                        <div class="form-group ">
                            <label for="cname" class="control-label col-lg-2">Kategori İsmi Güncelleyiniz</label>
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x=>x.CategoryName,new {@class="form-control"})
                               
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="cemail" class="control-label col-lg-2">E-Mail (required)</label>
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x => x.Description, new {@class="form-control" })
                                
                            </div>
                        </div>
                      
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-info">Kaydet</button>
                            </div>
                        </div>
                    }



                  
                </div>

            </div>
        </section>
    </div>
</div>